// `sightmap-webmcp init` — scaffold a draft tool manifest from a corpus.
// The draft is a starting point for the authoring loop in the
// sightmap-webmcp skill, not a finished manifest: every generated tool is
// marked TODO and needs the human/agent pass that decides what the site's
// real user goals are.

const yaml = require("js-yaml");

function slugify(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

// Collect up to `max` property-bearing components applicable on a view.
function readableComponents(corpus, viewName, max) {
  const out = [];
  for (const [crumb, entries] of corpus.components) {
    const applicable = entries.filter(
      (e) => e.scope == null || e.scope === viewName,
    );
    const scoped = applicable.filter((e) => e.scope != null);
    const use = scoped.length > 0 ? scoped : applicable;
    if (use.length !== 1) continue;
    const props = Object.keys(use[0].props);
    if (props.length === 0) continue;
    out.push({ crumb, prop: props[0] });
    if (out.length >= max) break;
  }
  return out;
}

function scaffold(corpus, opts) {
  const site = opts.site;
  const baseUrl = opts.baseUrl;
  const tools = [];

  for (const view of corpus.views.values()) {
    if (!view.url) continue;
    const name = `view_${slugify(view.name)}`.slice(0, 64);
    tools.push({
      name,
      description:
        `TODO: describe what this tool answers. Reads the ${view.name} view` +
        (view.description ? ` (${view.description})` : "") +
        ". Draft generated by sightmap-webmcp init — replace the fixed URL with a template and add params.",
      read_only: true,
      mode: "fetch",
      view: view.name,
      flow: [
        { navigate: view.url },
        {
          read: Object.fromEntries(
            readableComponents(corpus, view.name, 4).map(({ crumb, prop }) => [
              slugify(crumb.split(" ").pop()),
              { component: crumb, property: prop },
            ]),
          ),
        },
      ],
    });
  }

  for (const req of corpus.requests.values()) {
    const name = `api_${slugify(req.name)}`.slice(0, 64);
    const tool = {
      name,
      description:
        (req.description ? `${req.description} ` : "") +
        `TODO: confirm this endpoint is worth exposing, replace the url template, and declare params. (corpus request: ${req.name}, route: ${req.route})`,
      api: {
        request: req.name,
        url: `TODO-${req.route}`,
      },
    };
    tools.push(tool);
  }

  const manifest = {
    version: 1,
    site,
    base_url: baseUrl,
    description: `WebMCP tools for ${site} — draft scaffolded from its sightmap corpus.`,
    tools,
  };
  const header =
    "# Draft WebMCP tool manifest scaffolded by `sightmap-webmcp init`.\n" +
    "# Every tool below is a starting point: keep the ones that map to real\n" +
    "# user goals, delete the rest, and replace the TODOs. See the\n" +
    "# sightmap-webmcp skill for the authoring loop.\n";
  return header + yaml.dump(manifest, { lineWidth: 100, noRefs: true });
}

module.exports = { scaffold, slugify };
