// Browser-safe helpers for the WebMCP directory listings, the sibling of
// src/lib/atlas.ts. Deliberately free of node: imports and of any dependency
// on scripts/lib/directory.ts (which reads the filesystem and validates YAML),
// so this can be bundled and can also run under scripts/prerender.tsx.
//
// Everything here is presentation: grouping, labelling, formatting and the
// share/badge strings. Nothing classifies a tool — the `kind` was decided at
// review time and is Atlas's own classification, corrected on review.
import type { DirectoryListing, ScanTool, ToolKind } from '@/types/directory'

const SITE_ORIGIN = 'https://sightmap.org'

/** Human label for a tool kind. Sentence case; the chip CSS does not shout. */
export function kindLabel(kind: ToolKind): string {
  switch (kind) {
    case 'read':
      return 'Read'
    case 'action':
      return 'Action'
    case 'sensitive':
      return 'Sensitive'
  }
}

/**
 * Class list for a kind chip. Three distinct colours (green / yellow / accent)
 * rather than a scale, because these are categories, not grades — a
 * `sensitive` tool is not a worse tool, it is one whose call is harder to undo.
 */
export function kindClass(kind: ToolKind): string {
  return `atlas-kind atlas-kind--${kind}`
}

export interface ToolPageGroup {
  /** Route-scoped surface: the page path the tools were first seen on. */
  page: string
  tools: ScanTool[]
}

/**
 * Group the scan's tools by the page they were first seen on, in the order the
 * scan visited the pages. Route-scoped surfaces are a first-class idea in the
 * Atlas: "nine tools" says much less than "three on /, four on /search, two on
 * /account", so the page is the outer level and the tool is the inner one.
 *
 * A tool whose `page` matches no visited page still gets a group, appended in
 * first-seen order, so a scan can never silently drop a tool from the page.
 */
export function toolsByPage(listing: Pick<DirectoryListing, 'report'>): ToolPageGroup[] {
  const groups = new Map<string, ScanTool[]>()
  for (const page of listing.report.pages) {
    if (!groups.has(page.path)) groups.set(page.path, [])
  }
  for (const tool of listing.report.tools) {
    const bucket = groups.get(tool.page)
    if (bucket) bucket.push(tool)
    else groups.set(tool.page, [tool])
  }
  // A visited page with no tools is not interesting on this section; the facts
  // strip already says how many pages were checked.
  return [...groups.entries()].filter(([, tools]) => tools.length > 0).map(([page, tools]) => ({ page, tools }))
}

export interface ShareUrls {
  /** Canonical listing URL, the thing every share target points at. */
  url: string
  x: string
  linkedin: string
}

/**
 * The share targets for one listing. Both networks take the URL as a query
 * param, so the listing URL is built once and encoded once per target.
 *
 * The tweet text is factual on purpose — a tool count and the site name. No
 * "verified", no "safe": a listing is evidence a scan found these tools on the
 * date shown.
 */
export function shareUrls(listing: Pick<DirectoryListing, 'slug' | 'name' | 'counts'>): ShareUrls {
  const url = `${SITE_ORIGIN}/atlas/${listing.slug}`
  const n = listing.counts.tools
  const text = `${listing.name} exposes ${n} callable WebMCP ${n === 1 ? 'tool' : 'tools'}, scanned by Sightmap Atlas.`
  return {
    url,
    x: `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,
    linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
  }
}

/**
 * The embeddable badge, as markdown a maintainer pastes into their README.
 * The image is generated by scripts/build-atlas.ts at /atlas/<slug>/badge.svg
 * and the link goes back to the listing, so the badge is always checkable.
 */
export function badgeMarkdown(slug: string, name: string): string {
  const alt = `${name} on Sightmap Atlas`.replace(/[[\]]/g, '')
  return `[![${alt}](${SITE_ORIGIN}/atlas/${slug}/badge.svg)](${SITE_ORIGIN}/atlas/${slug})`
}

export interface ChecksTally {
  passed: number
  total: number
}

/** `x of y` for the checks section header. Facts, not a grade. */
export function checksPassed(listing: Pick<DirectoryListing, 'report'>): ChecksTally {
  const checks = listing.report.checks
  return { passed: checks.filter((c) => c.ok).length, total: checks.length }
}

/**
 * Format a scan timestamp. Listings carry two date shapes — `scannedAt` is a
 * full ISO instant and `added`/`updated` are date-only — and both land in the
 * same rails, so this takes either and prints one thing.
 *
 * Date-only strings are pinned to local midnight rather than parsed as UTC, so
 * a listing added on the 9th does not render as the 8th west of Greenwich.
 */
export function formatScanned(iso: string): string {
  if (!iso) return ''
  const dateOnly = /^\d{4}-\d{2}-\d{2}$/.test(iso)
  const d = new Date(dateOnly ? `${iso}T00:00:00` : iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
}
