// Turns content/blog/*.md into a typed manifest plus one HTML module per post.
// Drafts are included so /blog/<slug>?preview=true can render them; the app
// filters them out of the index and the prerender skips them entirely.
import fs from 'node:fs'
import path from 'node:path'
import { loadPosts, renderPostHtml } from './lib/posts'
import type { BlogPostMeta } from '../src/types/blog'

const CONTENT_DIR = path.resolve('content/blog')
const GENERATED_DIR = path.resolve('src/generated')
const POSTS_DIR = path.join(GENERATED_DIR, 'blog-posts')

async function main() {
  fs.rmSync(POSTS_DIR, { recursive: true, force: true })
  fs.mkdirSync(POSTS_DIR, { recursive: true })

  const posts = await loadPosts(CONTENT_DIR, { includeDrafts: true })
  const meta: BlogPostMeta[] = []

  for (const post of posts) {
    const html = await renderPostHtml(post.body)
    fs.writeFileSync(
      path.join(POSTS_DIR, `${post.frontmatter.slug}.ts`),
      `// Auto-generated by scripts/build-blog.ts — do not edit\nexport const html = ${JSON.stringify(html)}\n`
    )
    meta.push({
      ...post.frontmatter,
      readingTime: post.readingTime,
    })
    console.log(
      `  built ${post.frontmatter.slug} (${post.readingTime} min${post.frontmatter.draft ? ', draft' : ''})`
    )
  }

  fs.writeFileSync(
    path.join(GENERATED_DIR, 'blog-manifest.ts'),
    `// Auto-generated by scripts/build-blog.ts — do not edit\n` +
      `import type { BlogPostMeta } from '@/types/blog'\n\n` +
      `export const blogPosts: BlogPostMeta[] = ${JSON.stringify(meta, null, 2)}\n`
  )

  console.log(`\n  blog build complete: ${meta.length} post(s)`)
}

main().catch((err) => {
  console.error('Blog build failed:\n', err instanceof Error ? err.message : err)
  process.exit(1)
})
