// Turns the vendored src/data/atlas/ tree into the two things the site needs:
//
//   1. src/generated/atlas-manifest.ts — a typed manifest the app imports, the
//      same shape of generated module scripts/build-blog.ts produces for posts.
//   2. public/atlas/ — the servable side: screenshots, the verbatim index.json,
//      one verbatim `<slug>.md` per entry, and one `<slug>.tar.gz` holding that
//      entry's corpus. Vite copies public/ into dist/ untouched and `vite dev`
//      serves it, so this is what makes the images, the machine twins (P4.3),
//      and the install work in dev and in a build with no route handling of
//      their own.
//
// The tarball is what `sightmap atlas add <slug>` fetches. It is served from
// here rather than from raw.githubusercontent so a takedown binds both
// surfaces: an entry removed from the vendored tree stops being installable in
// the same rebuild that stops it being listed.
//
// public/atlas/ is generated and gitignored — it is wiped and rewritten on
// every run so a slug removed upstream (a takedown) actually disappears from
// dist/ instead of lingering as an orphaned file.
//
// The screenshots have to be copied rather than imported from src/: they are
// referenced from React components that scripts/prerender.tsx renders under
// tsx, where Vite's asset pipeline (`import.meta.glob`, `?url`) does not
// exist. public/ is the site's existing answer for that — content images for
// blog posts live there for the same reason.
import fs from 'node:fs'
import path from 'node:path'
import { atlasCategories, loadAtlas, resolveCorpus, resolveScreenshots } from './lib/atlas'
import { tarGz } from './lib/tar'

const DATA_DIR = path.resolve('src/data/atlas')
const GENERATED_DIR = path.resolve('src/generated')
const PUBLIC_DIR = path.resolve('public/atlas')

async function main() {
  const atlas = await loadAtlas(DATA_DIR)

  fs.rmSync(PUBLIC_DIR, { recursive: true, force: true })
  fs.mkdirSync(PUBLIC_DIR, { recursive: true })
  fs.mkdirSync(GENERATED_DIR, { recursive: true })

  // P4.3: /atlas/index.json, served byte-for-byte as vendored. Written from
  // the original text rather than re-serialized from the parsed object so the
  // route really is the file the atlas generator produced.
  fs.writeFileSync(path.join(PUBLIC_DIR, 'index.json'), atlas.indexJson)

  for (const entry of atlas.entries) {
    // P4.3: /atlas/<slug>.md — front matter plus body, verbatim.
    const md = atlas.markdown.get(entry.slug)
    if (md !== undefined) fs.writeFileSync(path.join(PUBLIC_DIR, `${entry.slug}.md`), md)

    const { files } = resolveScreenshots(DATA_DIR, entry.slug, entry.screenshots)
    if (files.length > 0) {
      const outDir = path.join(PUBLIC_DIR, 'screenshots', entry.slug)
      fs.mkdirSync(outDir, { recursive: true })
      for (const file of files) fs.copyFileSync(file, path.join(outDir, path.basename(file)))
    }

    // /atlas/<slug>.tar.gz — the corpus `sightmap atlas add` pulls. Same
    // per-entry, non-fatal contract as the schema check: a corpus that would
    // not install is left unpublished with a warning, and the rest of the site
    // ships. The page keeps rendering; the command on it 404s, which is the
    // honest outcome for an entry with nothing behind it.
    const corpus = resolveCorpus(DATA_DIR, entry.slug)
    let members = 0
    if (corpus.problems.length > 0) {
      console.warn(
        `  ! atlas entry ${entry.slug} publishes no corpus archive:\n` +
          corpus.problems.map((p) => `    - ${p}`).join('\n')
      )
    } else if (corpus.files.length === 0) {
      console.warn(`  ! atlas entry ${entry.slug} has no vendored .sightmap/ — sightmap atlas add will 404`)
    } else {
      // Packing reads community-vendored files off disk, so it stays inside
      // the per-entry contract: whatever goes wrong costs this entry its
      // archive, never the build.
      try {
        const archive = tarGz(corpus.files.map((f) => ({ name: f.name, body: fs.readFileSync(f.path) })))
        fs.writeFileSync(path.join(PUBLIC_DIR, `${entry.slug}.tar.gz`), archive)
        members = corpus.files.length
      } catch (err) {
        console.warn(
          `  ! atlas entry ${entry.slug} publishes no corpus archive: ${err instanceof Error ? err.message : err}`
        )
      }
    }

    console.log(
      `  built ${entry.slug} (${entry.stats.views} view(s), ${files.length} screenshot(s), ${members} corpus file(s)${
        md === undefined ? ', no README' : ''
      })`
    )
  }

  fs.writeFileSync(
    path.join(GENERATED_DIR, 'atlas-manifest.ts'),
    `// Auto-generated by scripts/build-atlas.ts — do not edit\n` +
      `import type { AtlasEntry } from '@/types/atlas'\n\n` +
      `export const atlasGeneratedAt = ${JSON.stringify(atlas.generatedAt)}\n\n` +
      `export const atlasEntries: AtlasEntry[] = ${JSON.stringify(atlas.entries, null, 2)}\n\n` +
      `export const atlasCategories: string[] = ${JSON.stringify(atlasCategories(atlas.entries))}\n`
  )

  const skipped = atlas.skipped.length > 0 ? `, ${atlas.skipped.length} skipped` : ''
  console.log(`\n  atlas build complete: ${atlas.entries.length} entry(s)${skipped}`)
}

main().catch((err) => {
  console.error('Atlas build failed:\n', err instanceof Error ? err.message : err)
  process.exit(1)
})
