package webmcp

// Emitter renders compiled IR into the three bundle formats. The snippet,
// module, and userscript wrappers differ only in how they load the shared
// runtime and IR.

//go:generate go run ./internal/gen

import (
	"crypto/sha256"
	_ "embed"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

// runtimeJS is the committed copy of webmcp/src/runtime/runtime.js at the
// repository root, regenerated by `go generate ./webmcp/...` (go:embed cannot
// reach outside the module — same pattern as go/skills). Do not edit it here.
//
//go:embed runtime.js
var runtimeJS string

// Formats lists the emit formats.
var Formats = []string{"snippet", "module", "userscript"}

// Provenance is the banner block written above every bundle (paths relative
// to the output file's directory, plus the corpus content hash).
type Provenance struct {
	GeneratorVersion string
	Manifest         string
	Corpus           string
	CorpusFiles      int
	CorpusHash       string
}

// CorpusHash is sha256 over each file's dir-relative path + "\n" + raw
// contents, in sorted path order. The banner prints this so a published
// userscript can be regenerated and diffed.
func CorpusHash(corpusDir string, files []string) (string, error) {
	h := sha256.New()
	for _, f := range files {
		rel, err := filepath.Rel(corpusDir, f)
		if err != nil {
			return "", err
		}
		h.Write([]byte(rel))
		h.Write([]byte("\n"))
		data, err := os.ReadFile(f)
		if err != nil {
			return "", err
		}
		h.Write(data)
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

func metaOf(ir *OM) *OM { return asOM(omGet(ir, "meta")) }

// oneLine collapses whitespace (newlines included) so authored text cannot
// break out of a // comment line or a userscript header field.
func oneLine(s string) string {
	return strings.TrimSpace(wsRe.ReplaceAllString(s, " "))
}

var wsRe = regexp.MustCompile(`\s+`)

func banner(ir *OM, p Provenance) string {
	meta := metaOf(ir)
	var lines []string
	lines = append(lines, fmt.Sprintf("// %s — WebMCP tools generated from a sightmap corpus.", asString(omGet(meta, "site"))))
	if desc := asString(omGet(meta, "description")); desc != "" {
		lines = append(lines, "// "+oneLine(desc))
	}
	var names []string
	for _, t := range asList(omGet(ir, "tools")) {
		names = append(names, asString(omGet(asOM(t), "name")))
	}
	lines = append(lines,
		"// tools: "+strings.Join(names, ", "),
		fmt.Sprintf("// generator: sightmap webmcp v%s (github.com/sightmap/sightmap)", p.GeneratorVersion),
		fmt.Sprintf("// manifest: %s | corpus: %s (%d files, sha256:%s)", p.Manifest, p.Corpus, p.CorpusFiles, p.CorpusHash[:12]),
		"// DO NOT EDIT — edit the manifest or corpus and regenerate: sightmap webmcp generate",
	)
	return strings.Join(lines, "\n")
}

// jsOrigin reproduces the JS `new URL(u).origin` for http(s) URLs.
func jsOrigin(baseURL string) string {
	u, err := url.Parse(baseURL)
	if err != nil {
		return baseURL
	}
	host := u.Host
	if (u.Scheme == "https" && strings.HasSuffix(host, ":443")) ||
		(u.Scheme == "http" && strings.HasSuffix(host, ":80")) {
		host = host[:strings.LastIndex(host, ":")]
	}
	return u.Scheme + "://" + host
}

func userscriptHeader(ir *OM) string {
	meta := metaOf(ir)
	site := asString(omGet(meta, "site"))
	origin := jsOrigin(asString(omGet(meta, "baseUrl")))
	var matches []string
	if m := asList(omGet(meta, "match")); len(m) > 0 {
		for _, v := range m {
			matches = append(matches, asString(v))
		}
	} else {
		matches = []string{origin + "/*"}
	}
	desc := oneLine(asString(omGet(meta, "description")))
	if desc == "" {
		desc = fmt.Sprintf("WebMCP tools for %s, generated from its sightmap corpus.", site)
	}
	lines := []string{
		"// ==UserScript==",
		fmt.Sprintf("// @name         %s WebMCP tools (sightmap)", site),
		"// @namespace    https://sightmap.org/webmcp",
		fmt.Sprintf("// @version      %s", asString(omGet(meta, "toolVersion"))),
		fmt.Sprintf("// @description  %s", desc),
	}
	for _, m := range matches {
		lines = append(lines, "// @match        "+m)
	}
	lines = append(lines, "// @run-at       document-idle", "// @grant        none", "// @noframes", "// ==/UserScript==")
	return strings.Join(lines, "\n")
}

// bundledRuntime is the runtime up to the [emit-strip-below] marker; the
// CommonJS export guard after it exists only for the jest tests and must not
// reach pages (a leaked global `module` would have its exports clobbered).
func bundledRuntime() string {
	src := runtimeJS
	if cut := strings.Index(src, "// [emit-strip-below]"); cut != -1 {
		src = src[:cut]
	}
	return strings.TrimRightFunc(src, unicode.IsSpace)
}

func bundleBody(ir *OM) string {
	// "</" is escaped as "<\/" (a legal JSON + JS escape) so authored content
	// can never terminate an inline <script> that serves the snippet.
	meta := strings.ReplaceAll(StringifyJSON(metaOf(ir)), "</", "<\\/")
	toolsV, _ := ir.Get("tools")
	tools := strings.ReplaceAll(StringifyJSON(toolsV), "</", "<\\/")
	return strings.Join([]string{
		"(() => {",
		`  "use strict";`,
		"",
		bundledRuntime(),
		"",
		"const __SMW_META = " + meta + ";",
		"",
		"const __SMW_TOOLS = " + tools + ";",
		"",
		"__smwBoot(__SMW_META, __SMW_TOOLS);",
		"})();",
	}, "\n")
}

// Emit renders one format.
func Emit(ir *OM, format string, p Provenance) (string, error) {
	body := bundleBody(ir)
	head := banner(ir, p)
	switch format {
	case "snippet":
		return head + "\n" + body + "\n", nil
	case "module":
		return head + "\n" + body + "\nexport {};\n", nil
	case "userscript":
		return userscriptHeader(ir) + "\n" + head + "\n" + body + "\n", nil
	}
	return "", fmt.Errorf("unknown format %q (snippet|module|userscript)", format)
}

// DefaultFileName is the per-format output name for a site slug.
func DefaultFileName(site, format string) string {
	switch format {
	case "snippet":
		return site + ".webmcp.js"
	case "module":
		return site + ".webmcp.module.js"
	default:
		return site + ".webmcp.user.js"
	}
}
