package webmcp

// The decisive test for this package: the Go generator must produce
// byte-identical bundles to the Node reference implementation at
// <repo>/webmcp. The committed example bundles were generated by the Node
// CLI, so regenerating them here and byte-comparing proves the two
// implementations agree on corpus semantics, manifest compilation, IR
// construction order, JSON serialization, and emission — all at once.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "webmcp", "package.json")); err != nil {
		t.Skipf("repository root with webmcp/ not found at %s", root)
	}
	return root
}

func firstDiff(a, b string) string {
	limit := len(a)
	if len(b) < limit {
		limit = len(b)
	}
	for i := 0; i < limit; i++ {
		if a[i] != b[i] {
			start := i - 80
			if start < 0 {
				start = 0
			}
			endA, endB := i+80, i+80
			if endA > len(a) {
				endA = len(a)
			}
			if endB > len(b) {
				endB = len(b)
			}
			return fmt.Sprintf("first divergence at byte %d:\n  go:   ...%q...\n  node: ...%q...", i, a[start:endA], b[start:endB])
		}
	}
	return fmt.Sprintf("lengths differ: go=%d node=%d (common prefix identical)", len(a), len(b))
}

func TestGoldenExamplesMatchNodeOutput(t *testing.T) {
	root := repoRoot(t)
	examplesDir := filepath.Join(root, "webmcp", "examples")
	entries, err := os.ReadDir(examplesDir)
	if err != nil {
		t.Fatal(err)
	}
	tested := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		site := e.Name()
		t.Run(site, func(t *testing.T) {
			dir := filepath.Join(examplesDir, site)
			toolsFile := filepath.Join(dir, "webmcp.tools.yaml")

			manifest, errs, _, err := LoadManifest(toolsFile)
			if err != nil {
				t.Fatal(err)
			}
			if len(errs) > 0 {
				t.Fatalf("manifest errors: %s", strings.Join(errs, "; "))
			}
			corpusDir := filepath.Join(dir, ManifestSightmapDir(manifest))
			corpus, err := LoadCorpus(corpusDir)
			if err != nil {
				t.Fatal(err)
			}
			ir, cerrs, _ := Compile(corpus, manifest)
			if len(cerrs) > 0 {
				t.Fatalf("compile errors: %s", strings.Join(cerrs, "; "))
			}

			hash, err := CorpusHash(corpus.Dir, corpus.Files)
			if err != nil {
				t.Fatal(err)
			}
			manifestRel, _ := filepath.Rel(dir, toolsFile)
			corpusRel, _ := filepath.Rel(dir, corpus.Dir)
			for _, format := range Formats {
				outFile := filepath.Join(dir, DefaultFileName(SiteOf(ir), format))
				want, err := os.ReadFile(outFile)
				if err != nil {
					t.Fatalf("committed bundle missing: %v", err)
				}
				got, err := Emit(ir, format, Provenance{
					GeneratorVersion: GeneratorVersion,
					Manifest:         manifestRel,
					Corpus:           corpusRel,
					CorpusFiles:      len(corpus.Files),
					CorpusHash:       hash,
				})
				if err != nil {
					t.Fatal(err)
				}
				if got != string(want) {
					t.Errorf("%s: Go output differs from committed Node output\n%s",
						filepath.Base(outFile), firstDiff(got, string(want)))
				}
			}
		})
		tested++
	}
	if tested == 0 {
		t.Fatal("no example directories found")
	}
}

func TestFixtureCompiles(t *testing.T) {
	root := repoRoot(t)
	fixture := filepath.Join(root, "webmcp", "test", "fixtures", "site")
	manifest, errs, warns, err := LoadManifest(filepath.Join(fixture, "webmcp.tools.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(errs) > 0 {
		t.Fatalf("manifest errors: %v", errs)
	}
	corpus, err := LoadCorpus(filepath.Join(fixture, ".sightmap"))
	if err != nil {
		t.Fatal(err)
	}
	ir, cerrs, cwarns := Compile(corpus, manifest)
	if len(cerrs) > 0 {
		t.Fatalf("compile errors: %v", cerrs)
	}
	if len(warns)+len(cwarns) > 0 {
		t.Fatalf("unexpected warnings: %v %v", warns, cwarns)
	}
	names := ToolNames(ir)
	want := []string{"search", "search_api", "stock", "buy_first_match"}
	if strings.Join(names, ",") != strings.Join(want, ",") {
		t.Fatalf("tools = %v, want %v", names, want)
	}
}

func TestScaffoldValidatesAgainstItsCorpus(t *testing.T) {
	root := repoRoot(t)
	corpusDir := filepath.Join(root, "web", "src", "data", "atlas", "ikea", ".sightmap")
	if _, err := os.Stat(corpusDir); err != nil {
		t.Skip("atlas corpus not present")
	}
	corpus, err := LoadCorpus(corpusDir)
	if err != nil {
		t.Fatal(err)
	}
	out, err := Scaffold(corpus, "ikea", "https://www.ikea.com")
	if err != nil {
		t.Fatal(err)
	}
	doc, err := parseYAMLOrdered([]byte(out))
	if err != nil {
		t.Fatalf("scaffold output is not valid YAML: %v", err)
	}
	var d diags
	validateManifest(doc, &d)
	if len(d.errors) > 0 {
		t.Fatalf("scaffold output fails validation: %v", d.errors)
	}
	if _, cerrs, _ := Compile(corpus, doc); len(cerrs) > 0 {
		t.Fatalf("scaffold output fails compile: %v", cerrs)
	}
}
