package webmcp

// `sightmap webmcp init` — a port of webmcp/src/scaffold.js. Drafts a tool
// manifest from a corpus: one fetch-read tool per view with a representative
// URL, one api stub per corpus request, every one marked TODO. The YAML
// styling differs cosmetically from the Node scaffolder (yaml.v3 vs js-yaml);
// the content is the same and a draft is for editing anyway.

import (
	"fmt"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

var slugSplitRe = regexp.MustCompile(`([a-z0-9])([A-Z])`)
var slugCleanRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(name string) string {
	s := slugSplitRe.ReplaceAllString(name, "${1}_${2}")
	s = strings.ToLower(s)
	s = slugCleanRe.ReplaceAllString(s, "_")
	return strings.Trim(s, "_")
}

func strNode(s string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
	return n
}

func boolNode(b bool) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: fmt.Sprintf("%t", b)}
}

func intNode(i int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprintf("%d", i)}
}

func mapNode(pairs ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Content: pairs}
}

func seqNode(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Content: items}
}

// readableComponents collects up to max property-bearing components
// applicable on a view, in corpus index order.
func readableComponents(c *Corpus, viewName string, max int) [][2]string {
	var out [][2]string
	for _, crumb := range c.crumbSeq {
		use := entriesFor(c, crumb, viewName)
		if len(use) != 1 {
			continue
		}
		if len(use[0].PropOrder) == 0 {
			continue
		}
		out = append(out, [2]string{crumb, use[0].PropOrder[0]})
		if len(out) >= max {
			break
		}
	}
	return out
}

// Scaffold renders a draft manifest for the corpus.
func Scaffold(c *Corpus, site, baseURL string) (string, error) {
	tools := seqNode()

	for _, vname := range c.ViewOrder {
		view := c.Views[vname]
		if view.URL == "" {
			continue
		}
		name := "view_" + slugify(view.Name)
		if len(name) > 64 {
			name = name[:64]
		}
		desc := "TODO: describe what this tool answers. Reads the " + view.Name + " view"
		if view.Description != "" {
			desc += " (" + view.Description + ")"
		}
		desc += ". Draft generated by sightmap-webmcp init — replace the fixed URL with a template and add params."

		read := mapNode()
		for _, rc := range readableComponents(c, view.Name, 4) {
			crumb, prop := rc[0], rc[1]
			parts := strings.Split(crumb, " ")
			key := slugify(parts[len(parts)-1])
			read.Content = append(read.Content, strNode(key),
				mapNode(strNode("component"), strNode(crumb), strNode("property"), strNode(prop)))
		}
		tools.Content = append(tools.Content, mapNode(
			strNode("name"), strNode(name),
			strNode("description"), strNode(desc),
			strNode("read_only"), boolNode(true),
			strNode("mode"), strNode("fetch"),
			strNode("view"), strNode(view.Name),
			strNode("flow"), seqNode(
				mapNode(strNode("navigate"), strNode(view.URL)),
				mapNode(strNode("read"), read),
			),
		))
	}

	for _, rname := range c.ReqOrder {
		req := c.Requests[rname]
		name := "api_" + slugify(req.Name)
		if len(name) > 64 {
			name = name[:64]
		}
		desc := ""
		if req.Description != "" {
			desc = req.Description + " "
		}
		desc += fmt.Sprintf("TODO: confirm this endpoint is worth exposing, replace the url template, and declare params. (corpus request: %s, route: %s)", req.Name, req.Route)
		tools.Content = append(tools.Content, mapNode(
			strNode("name"), strNode(name),
			strNode("description"), strNode(desc),
			strNode("api"), mapNode(
				strNode("request"), strNode(req.Name),
				strNode("url"), strNode("TODO-"+req.Route),
			),
		))
	}

	root := mapNode(
		strNode("version"), intNode(1),
		strNode("site"), strNode(site),
		strNode("base_url"), strNode(baseURL),
		strNode("description"), strNode(fmt.Sprintf("WebMCP tools for %s — draft scaffolded from its sightmap corpus.", site)),
		strNode("tools"), tools,
	)

	var sb strings.Builder
	sb.WriteString("# Draft WebMCP tool manifest scaffolded by `sightmap-webmcp init`.\n")
	sb.WriteString("# Every tool below is a starting point: keep the ones that map to real\n")
	sb.WriteString("# user goals, delete the rest, and replace the TODOs. See the\n")
	sb.WriteString("# sightmap-webmcp skill for the authoring loop.\n")
	enc := yaml.NewEncoder(&sb)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return "", err
	}
	if err := enc.Close(); err != nil {
		return "", err
	}
	return sb.String(), nil
}
