// Code generated by go generate ./webmcp/...; DO NOT EDIT.
// Source: <repo>/webmcp/package.json.

package webmcp

// GeneratorVersion appears in every bundle's provenance banner.
const GeneratorVersion = "0.1.0"
