// Code generated by go generate ./webmcp/...; DO NOT EDIT.
// Source: <repo>/webmcp/package.json.

package webmcp

// GeneratorVersion is the @sightmap/webmcp-codegen version this generator
// mirrors; it appears verbatim in every bundle's provenance banner, so the Go
// and Node generators stay byte-identical.
const GeneratorVersion = "0.1.0"
