// Domain-control claim for an Atlas submission.
//
// The owner adds one comment line to the file WebMCP clients already read:
//
//     # sightmap-claim: <32 lowercase hex characters>
//
// and passes the same token to the submit endpoint. Fetching the file and
// finding the line is the whole check.
//
// The token is generated by the owner (`openssl rand -hex 16`) and only ever
// compared: it is never stored on a record, written to a log line, or echoed
// into a response or an error reason — anyone holding it could claim the host,
// so it must not outlive the request that carried it.
//
// This proves that someone who can publish files on the host asked to be
// scanned. It is not a statement that the site is safe, reviewed, or endorsed;
// admission to the Atlas is a separate step a maintainer performs.

import { sameSite } from '../../scripts/lib/scan.ts'
import { CLAIM_TOKEN_PATTERN } from '../../src/lib/submit-types.ts'

/** 16 random bytes, hex. Anything else is a client mistake, not a failed claim. */
export const CLAIM_TOKEN_RE = new RegExp(`^${CLAIM_TOKEN_PATTERN}$`)

export const CLAIM_FILE = '/webmcp.txt'

/** A canonical-host or protocol redirect is normal; a chain of four is not. */
export const CLAIM_MAX_REDIRECTS = 3

/** The submitter is waiting on this request, so the whole check is budgeted. */
export const CLAIM_TIMEOUT_MS = 5_000

/** `webmcp.txt` is a short text file; anything larger is not one. */
export const CLAIM_MAX_BYTES = 64 * 1024

const REDIRECT_STATUS = new Set([301, 302, 303, 307, 308])

export type ClaimFailure = 'claim-unreachable' | 'claim-mismatch'

export type ClaimResult = { ok: true } | { ok: false; code: ClaimFailure; reason: string }

export interface ClaimOptions {
  timeoutMs?: number
  maxBytes?: number
  maxRedirects?: number
}

const unreachable = (reason: string): ClaimResult => ({ ok: false, code: 'claim-unreachable', reason })
const mismatch = (reason: string): ClaimResult => ({ ok: false, code: 'claim-mismatch', reason })

/** Where the claim file lives for a submitted URL. Port is kept; path is not. */
export function claimUrl(input: string): string {
  const withScheme = /^[a-z][a-z0-9+.-]*:/i.test(input) ? input : `https://${input}`
  const u = new URL(withScheme)
  return `https://${u.host}${CLAIM_FILE}`
}

/**
 * The claim line, anywhere in the file. `#` comments are ignored by every
 * `webmcp.txt` parser, so carrying the token there costs the owner nothing.
 * The token is interpolated raw because callers validate it against
 * `CLAIM_TOKEN_RE` first — hex has no regex metacharacters.
 */
export function claimLine(token: string): RegExp {
  return new RegExp(`^#\\s*sightmap-claim:\\s*${token}\\s*$`, 'm')
}

export function hasClaim(body: string, token: string): boolean {
  return CLAIM_TOKEN_RE.test(token) && claimLine(token).test(body)
}

/**
 * Read at most `maxBytes` of a response body. Returns null when the file is
 * bigger than that: a `webmcp.txt` that size is not the file we asked for, and
 * reading the rest of it is work an unknown host should not be able to demand.
 */
async function readCapped(res: Response, maxBytes: number): Promise<string | null> {
  const declared = Number(res.headers.get('content-length'))
  if (Number.isFinite(declared) && declared > maxBytes) return null
  if (!res.body) return ''

  const reader = res.body.getReader()
  const chunks: Uint8Array[] = []
  let size = 0
  try {
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      if (!value) continue
      size += value.byteLength
      if (size > maxBytes) return null
      chunks.push(value)
    }
  } finally {
    await reader.cancel().catch(() => {})
  }

  const joined = new Uint8Array(size)
  let offset = 0
  for (const chunk of chunks) {
    joined.set(chunk, offset)
    offset += chunk.byteLength
  }
  return new TextDecoder().decode(joined)
}

/**
 * Fetch `https://<host>/webmcp.txt` and look for the claim line.
 *
 * Redirects are followed by hand (`redirect: 'manual'`) rather than by the
 * runtime, because the only thing worth following is the site's own canonical
 * host: a claim that can be satisfied by redirecting to a file on someone
 * else's server is not a claim on this host. Each hop is checked with the same
 * `www.` rule the scanner applies to a first-load redirect.
 */
export async function verifyClaim(
  url: string,
  token: string,
  fetchImpl: typeof fetch = fetch,
  opts: ClaimOptions = {}
): Promise<ClaimResult> {
  const maxBytes = opts.maxBytes ?? CLAIM_MAX_BYTES
  const maxRedirects = opts.maxRedirects ?? CLAIM_MAX_REDIRECTS
  const timeoutMs = opts.timeoutMs ?? CLAIM_TIMEOUT_MS

  if (!CLAIM_TOKEN_RE.test(token)) return mismatch('claim token is malformed')

  let target: string
  try {
    target = claimUrl(url)
  } catch {
    return unreachable('submitted URL has no host')
  }

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    for (let hop = 0; hop <= maxRedirects; hop += 1) {
      const res = await fetchImpl(target, {
        method: 'GET',
        redirect: 'manual',
        signal: controller.signal,
        headers: { accept: 'text/plain, */*' },
      })

      if (REDIRECT_STATUS.has(res.status)) {
        const location = res.headers.get('location')
        if (!location) return unreachable(`HTTP ${res.status} with no Location header`)
        let next: string
        try {
          next = new URL(location, target).toString()
        } catch {
          return unreachable('redirect Location is not a URL')
        }
        if (!sameSite(target, next)) return unreachable('redirected off-site')
        target = next
        continue
      }

      if (res.status !== 200) return unreachable(`HTTP ${res.status}`)

      const body = await readCapped(res, maxBytes)
      if (body === null) return unreachable(`${CLAIM_FILE} is larger than ${maxBytes} bytes`)
      return hasClaim(body, token)
        ? { ok: true }
        : mismatch(`no matching claim line in ${CLAIM_FILE}`)
    }
    return unreachable(`more than ${maxRedirects} redirects`)
  } catch (err) {
    if (controller.signal.aborted) return unreachable(`timed out after ${timeoutMs} ms`)
    return unreachable(err instanceof Error ? err.message : String(err))
  } finally {
    clearTimeout(timer)
  }
}
